env:
  browser: true
  es6: true
extends: airbnb-base
parser: babel-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {
  react/jsx-uses-react: 1,
  react/jsx-uses-vars: 1,
  react/jsx-filename-extension: [1, { extensions: ['.js', '.jsx'] }],
  class-methods-use-this: 0,
  jsx-quotes: [2, "prefer-single"],
  no-mixed-spaces-and-tabs: 2,
  no-console: 2,
  no-constant-condition: 2,
  no-debugger: 2,
  no-irregular-whitespace: 2,
  no-multi-spaces: 2,
  indent: [2, 2, {SwitchCase: 1}],
  no-lonely-if: 0,
  no-plusplus: 0,
  radix: 0,
  import/no-extraneous-dependencies: 0,
  import/no-unresolved: 0
}
